name: Build, Deploy, and Invalidate

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: /tmp/output

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout shorty
        uses: actions/checkout@master
        with:
          repository: grahamgilbert/shorty
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false

      - name: Build site
        run: |
          python3 shorty.py -c config.json -o /tmp/_site

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync /tmp/output/_site s3://grahamat/ --delete --acl public-read
      
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths /