name: Build, Deploy, and Invalidate

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout shorty
        uses: actions/checkout@master
        with:
          repository: grahamgilbert/shorty
          path: shorty

      - name: Run shorty
        run: |
          python3 shorty/shorty.py -c config.json -o /tmp/_site

      - name: Configure AWS credentials
        run: |
          aws configure set region "us-east-1"
          aws --profile default configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws --profile default configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws sts get-caller-identity >/dev/null 2>&1

      - name: Upload to S3
        run: aws s3 sync /tmp/_site s3://grahamat/ --delete --acl public-read
      
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths /