name: Build, Deploy, and Invalidate

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: /tmp/output

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker image
        run: docker pull grahamgilbert/shorty:1.0.1

      - name: Build site
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tmp/output \
            grahamgilbert/shorty:1.0.1 \
            /usr/local/bin/shorty -c /tmp/output/config.json -o /tmp/output/_site

      - name: Persist workspace
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: /tmp/output/_site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    defaults:
      run:
        working-directory: /tmp/output

    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: /tmp/output/_site

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync /tmp/output/_site s3://grahamat/ --delete --acl public-read

  invalidate:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths /
