name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout shorty
        uses: actions/checkout@master
        with:
          repository: grahamgilbert/shorty
          path: shorty

      - name: Run shorty
        run: |
          python3 shorty/shorty.py -c config.json -o /tmp/_site

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set region "us-east-1"
          aws sts get-caller-identity >/dev/null 2>&1
